name: Parkplätze messen

on:
 schedule:
    - cron: "0 7-21 * * *"
      timezone: "Europe/Berlin"

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Messen
        run: ./run.sh

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add parkplatzdaten.csv

          # only commit if there are changes
          git diff --cached --quiet && exit 0

          git commit -m "Neue Messung"
          git push